### ISSUE TITLE
IP for other devices then RPI

### ISSUE THREAD

**Issue by Natejoestev** [designshift/atem-tally-lite#57]
Hi, i have noticed there is no information on the IPs. so i can't get it to work on my Arduino.
is there any socket standard you use? is there a way to have a separate device (by IP) per camera? like:
```yaml
Camera1: 192.168.1.101
Camera2: 192.168.1.102
Camera3: 192.168.1.103
```
i'm basically just looking for a way to receive `Program` or `Preview` for each camera device.
